export type Product = {
  id: string
  name: string
  shortDescription: string
  price: number
  originalPrice?: number
  discountRate?: number
  imageUrl: string
  images: string[]
  category: "가구" | "전자기기" | "악세사리"
  tags: string[]
  rating?: number
  reviewCount?: number
  isSoldOut?: boolean
  seller?: string
  detailDescription?: string
}

export const products: Product[] = [
  {
    id: "1",
    name: "에르고노믹 메쉬 체어 프리미엄",
    shortDescription: "장시간 앉아도 편안한 인체공학적 설계",
    price: 289000,
    originalPrice: 359000,
    discountRate: 20,
    imageUrl: "/ergonomic-mesh-chair.jpg",
    images: ["/ergonomic-mesh-chair.jpg", "/ergonomic-mesh-chair.jpg", "/ergonomic-mesh-chair.jpg"],
    category: "가구",
    tags: ["오피스", "인체공학", "프리미엄"],
    rating: 4.8,
    reviewCount: 1247,
    seller: "DESKIT Official",
    detailDescription: "프리미엄 메쉬 소재와 인체공학적 설계로 장시간 작업 시에도 편안함을 유지합니다.",
  },
  {
    id: "2",
    name: "USB-C 도킹 스테이션 11포트",
    shortDescription: "노트북을 데스크탑처럼 사용하는 멀티포트",
    price: 129000,
    originalPrice: 169000,
    discountRate: 24,
    imageUrl: "/usb-c-docking-station.jpg",
    images: ["/usb-c-docking-station.jpg", "/usb-c-docking-station.jpg", "/usb-c-docking-station.jpg"],
    category: "전자기기",
    tags: ["연결성", "USB-C", "멀티포트"],
    rating: 4.6,
    reviewCount: 892,
    seller: "TechHub Korea",
    detailDescription: "11개의 포트로 모든 주변기기를 한 번에 연결하세요.",
  },
  {
    id: "3",
    name: "기계식 키보드 RGB 청축",
    shortDescription: "타건감과 RGB 조명이 어우러진 게이밍 키보드",
    price: 159000,
    imageUrl: "/mechanical-keyboard-rgb.jpg",
    images: ["/mechanical-keyboard-rgb.jpg", "/mechanical-keyboard-rgb.jpg", "/mechanical-keyboard-rgb.jpg"],
    category: "전자기기",
    tags: ["게이밍", "RGB", "기계식"],
    rating: 4.9,
    reviewCount: 2156,
    seller: "GameGear Store",
    detailDescription: "정확한 타건감의 청축 스위치와 화려한 RGB 백라이트를 제공합니다.",
  },
  {
    id: "4",
    name: "무선 마우스 게이밍 프로",
    shortDescription: "프로게이머가 선택한 무선 게이밍 마우스",
    price: 89000,
    originalPrice: 119000,
    discountRate: 25,
    imageUrl: "/wireless-gaming-mouse.jpg",
    images: ["/wireless-gaming-mouse.jpg", "/wireless-gaming-mouse.jpg", "/wireless-gaming-mouse.jpg"],
    category: "전자기기",
    tags: ["게이밍", "무선", "고성능"],
    rating: 4.7,
    reviewCount: 1523,
    seller: "GameGear Store",
    detailDescription: "25,000 DPI 센서와 80시간 배터리로 완벽한 게이밍 경험을 제공합니다.",
  },
  {
    id: "5",
    name: "27인치 4K 모니터 IPS",
    shortDescription: "선명한 화질의 프리미엄 디스플레이",
    price: 449000,
    originalPrice: 599000,
    discountRate: 25,
    imageUrl: "/27-inch-4k-monitor.jpg",
    images: ["/27-inch-4k-monitor.jpg", "/27-inch-4k-monitor.jpg", "/27-inch-4k-monitor.jpg"],
    category: "전자기기",
    tags: ["모니터", "4K", "IPS"],
    rating: 4.8,
    reviewCount: 756,
    seller: "DisplayMax",
    detailDescription: "4K UHD 해상도와 IPS 패널로 정확한 색상 재현을 경험하세요.",
  },
  {
    id: "6",
    name: "LED 데스크 라이트 조명",
    shortDescription: "눈 건강을 지키는 스마트 조명",
    price: 59000,
    imageUrl: "/led-desk-lamp.jpg",
    images: ["/led-desk-lamp.jpg", "/led-desk-lamp.jpg", "/led-desk-lamp.jpg"],
    category: "악세사리",
    tags: ["조명", "LED", "눈보호"],
    rating: 4.5,
    reviewCount: 2341,
    seller: "LightCraft",
    detailDescription: "무단계 밝기 조절과 자동 색온도 조절 기능을 갖춘 스마트 조명입니다.",
  },
  {
    id: "7",
    name: "스탠딩 데스크 전동 높이조절",
    shortDescription: "건강한 업무 환경을 위한 전동 스탠딩 데스크",
    price: 589000,
    originalPrice: 799000,
    discountRate: 26,
    imageUrl: "/electric-standing-desk.jpg",
    images: ["/electric-standing-desk.jpg", "/electric-standing-desk.jpg", "/electric-standing-desk.jpg"],
    category: "가구",
    tags: ["스탠딩", "전동", "건강"],
    rating: 4.9,
    reviewCount: 412,
    seller: "DESKIT Official",
    detailDescription: "버튼 하나로 쉽게 높이를 조절할 수 있는 전동 스탠딩 데스크입니다.",
  },
  {
    id: "8",
    name: "노트북 거치대 알루미늄",
    shortDescription: "우아한 디자인의 알루미늄 거치대",
    price: 45000,
    imageUrl: "/aluminum-laptop-stand.jpg",
    images: ["/aluminum-laptop-stand.jpg", "/aluminum-laptop-stand.jpg", "/aluminum-laptop-stand.jpg"],
    category: "악세사리",
    tags: ["거치대", "알루미늄", "미니멀"],
    rating: 4.6,
    reviewCount: 1876,
    seller: "DESKIT Official",
    detailDescription: "고급 알루미늄 소재로 제작된 우아한 노트북 거치대입니다.",
  },
  {
    id: "9",
    name: "케이블 정리 박스 세트",
    shortDescription: "깔끔한 데스크를 위한 케이블 정리 솔루션",
    price: 29000,
    originalPrice: 39000,
    discountRate: 26,
    imageUrl: "/cable-management-box.jpg",
    images: ["/cable-management-box.jpg", "/cable-management-box.jpg", "/cable-management-box.jpg"],
    category: "악세사리",
    tags: ["정리", "미니멀", "감성"],
    rating: 4.4,
    reviewCount: 3214,
    seller: "OrganizeIt",
    detailDescription: "지저분한 케이블을 깔끔하게 정리할 수 있는 정리 박스 세트입니다.",
  },
  {
    id: "10",
    name: "웹캠 4K 스트리밍 프로",
    shortDescription: "스트리밍과 화상회의를 위한 4K 웹캠",
    price: 189000,
    imageUrl: "/4k-streaming-webcam.jpg",
    images: ["/4k-streaming-webcam.jpg", "/4k-streaming-webcam.jpg", "/4k-streaming-webcam.jpg"],
    category: "전자기기",
    tags: ["웹캠", "4K", "스트리밍"],
    rating: 4.7,
    reviewCount: 634,
    isSoldOut: true,
    seller: "StreamPro",
    detailDescription: "4K 해상도와 자동 초점 기능으로 선명한 화질을 제공합니다.",
  },
  {
    id: "11",
    name: "블루투스 스피커 데스크용",
    shortDescription: "컴팩트한 사이즈, 풍부한 사운드",
    price: 79000,
    originalPrice: 99000,
    discountRate: 20,
    imageUrl: "/bluetooth-desk-speaker.jpg",
    images: ["/bluetooth-desk-speaker.jpg", "/bluetooth-desk-speaker.jpg", "/bluetooth-desk-speaker.jpg"],
    category: "전자기기",
    tags: ["스피커", "블루투스", "오디오"],
    rating: 4.5,
    reviewCount: 1128,
    seller: "SoundWave",
    detailDescription: "작은 크기에서 나오는 강력한 사운드를 경험하세요.",
  },
  {
    id: "12",
    name: "모니터 암 듀얼 거치대",
    shortDescription: "공간 활용을 극대화하는 듀얼 모니터 암",
    price: 129000,
    imageUrl: "/dual-monitor-arm.jpg",
    images: ["/dual-monitor-arm.jpg", "/dual-monitor-arm.jpg", "/dual-monitor-arm.jpg"],
    category: "악세사리",
    tags: ["모니터암", "듀얼", "공간활용"],
    rating: 4.8,
    reviewCount: 987,
    seller: "DESKIT Official",
    detailDescription: "듀얼 모니터를 자유롭게 배치하고 책상 공간을 넓게 사용하세요.",
  },
]
